### ISSUE TITLE
提供一个爬取图片的例子

### ISSUE THREAD

**Issue by pkwenda** [java-webbee/webBee#29]
提供一个爬取图片的例子，批量爬取

**Comment by wangtonghe** [comment]
@pkwenda 图片批量爬取可参考HuabanImgDemo。另，对于图片视频等的爬取，建议应和爬取内容的方式尽量一致。爬取工作只负责寻找图片或视频的url,找到后直接交给专门的文件下载处理器去处理。这样思路也比较清晰。

**Comment by pkwenda** [comment]
也可以，我这边重构Task并提供一个newRequest函数方便你在`专门的文件下载处理器`正确的产生请求，毕竟用`URL`来获取的流连content-type都没有，无法自动配置mineType，达到自动化的目的
``` java
if (destPath.endsWith("/")) {
                destPath = destPath.substring(0, destPath.length() - 1);
            }
```
```
 byte[] buffer = new byte[1024];
```
这部分，我会在不影响你的功能基础上抽离出来，我觉得可以抽离的抽离出来，因为可能很多地方要用。

这个问题我们去 #33 讨论。包括今后以后所有的问题，我觉得我们尽量在github讨论。

**Comment by wangtonghe** [comment]
@pkwenda  好的。刚看到这个。昨天我也发现url直接下载的方式不能直接获取文件类型，后用判断流开始字节的部分暂时获得了文件类型。类似[这样的处理](http://www.cnblogs.com/liaojie970/p/5010786.html)。不过感觉不太优雅。你既提供，那就直接用你的了。再讨论。
